// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA96sIOeTl05ln_LKDR-RpJqdnBTnW4Vsg',
    appId: '1:43890043330:web:8c0bd63c935e863b358e5b',
    messagingSenderId: '43890043330',
    projectId: 'ghumo-703ae',
    authDomain: 'ghumo-703ae.firebaseapp.com',
    storageBucket: 'ghumo-703ae.appspot.com',
    measurementId: 'G-WDDEWGGQCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqcovfQjJXQnYOWr66oQzeDarEfSHaTuY',
    appId: '1:43890043330:android:4d3ea8548bec5ef3358e5b',
    messagingSenderId: '43890043330',
    projectId: 'ghumo-703ae',
    storageBucket: 'ghumo-703ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmBQP9xSrmP4Hr0z3jizCu-2t3QM9acMk',
    appId: '1:43890043330:ios:d88d3561cdddf920358e5b',
    messagingSenderId: '43890043330',
    projectId: 'ghumo-703ae',
    storageBucket: 'ghumo-703ae.appspot.com',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmBQP9xSrmP4Hr0z3jizCu-2t3QM9acMk',
    appId: '1:43890043330:ios:8e994947af99fbcd358e5b',
    messagingSenderId: '43890043330',
    projectId: 'ghumo-703ae',
    storageBucket: 'ghumo-703ae.appspot.com',
    iosBundleId: 'com.example.driver.RunnerTests',
  );
}
